### ISSUE TITLE
libtorch: nproc: not found

### ISSUE THREAD

**Issue by hokim72** [t-kuha/recipes-ml#1]
In petalinux 2020.2, the following error happened

`ERROR: libtorch-1.7.0-r0 do_configure: Execution of '/home/hokim/work/vitis_ai/petalinux/ultra96/build/tmp/work/aarch64-xilinx-linux/libtorch/1.7.0-r0/temp/run.do_configure.19292' failed with exit code 129:
/home/hokim/work/vitis_ai/petalinux/ultra96/build/tmp/work/aarch64-xilinx-linux/libtorch/1.7.0-r0/temp/run.do_configure.19292: 101: /home/hokim/work/vitis_ai/petalinux/ultra96/build/tmp/work/aarch64-xilinx-linux/libtorch/1.7.0-r0/temp/run.do_configure.19292: nproc: not found`

To fix it,  I add coreutils-native to DEPENDS in libtorch.bb

**Comment by t-kuha** [comment]
@hokim72 
Thank you for reporting the issue.
The recipe is now fixed in commit #b6e525a.
