### ISSUE TITLE
Question: Will installing libtorch also add pytorch to the Yocto image?

### ISSUE THREAD

**Issue by ENM185** [t-kuha/recipes-ml#2]
If not, do you know of a way to add it?

**Comment by t-kuha** [comment]
No, this recipe does not support Python part of PyTorch.
To add Python support, you have to enable Python in the recipe (i.e. ``-DBUILD_PYTHON=ON``).
Please note you may also have to build Python alongside PyTorch.

**Comment by przemoch-dev** [comment]
@ENM185 have you finally add PyTorch python lib to the Yocto image? I'm trying to do the same, without success

**Comment by t-kuha** [comment]
@ENM185 & @przemoch-dev 
Please try ``pytorch`` recipe, which was added in branch [2021.2](https://github.com/t-kuha/recipes-ml/tree/2021.2).

**Comment by t-kuha** [comment]
Closing this issue due to long inactivity
