### ISSUE TITLE
Yocto 2.4 support?

### ISSUE THREAD

**Issue by ZuzooVn** [t-kuha/recipes-ml#4]
Thanks for your great repo.

Can your TensorflowLite 1.15.5 work with Yocto Rocko 2.4 on Quectel SC20 (Qualcomm MSM8909 SoC (4x ARM Cortex A7, 32-bit))?

**Comment by t-kuha** [comment]
@ZuzooVn
I think the best way is to just give it a try.
The [2018.3 branch](https://github.com/t-kuha/recipes-ml/blob/2018.3/tflite/tflite.bb), which is for Yocto v2.4 Rocko, may better suit your situation...

**Comment by t-kuha** [comment]
Closed due to long inactivity.
