### ISSUE TITLE
Libtorch recipe

### ISSUE THREAD

**Issue by Shivaraj199** [t-kuha/recipes-ml#5]
Hello i am trying to use libtorch in my embedded linux application, I am not able to find any suitabke resources. I have the lib from the source. Can you please recipe for the libtorch?I am using the yocto dunfell branch.

**Comment by t-kuha** [comment]
@Shivaraj199 
Please take a look at 2021.2 branch. As this branch is for Gatesgrath, you may need some tweaking.
