### ISSUE TITLE
PyTorch: Upgrade to 2.0

### ISSUE THREAD

**Issue by miili** [t-kuha/recipes-ml#7]
PyTorch version 2.0 was released, which is more or less backwards compat w v1.

**Comment by t-kuha** [comment]
I have updated the recipe for PyTorch v2.0.0 @ [edce909](https://github.com/t-kuha/recipes-ml/commit/edce909c295bea7c1c9495bb66b3f2fe2d88f2ba)

**Comment by miili** [comment]
awesome, thanks a bunch!
